# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(940, 633)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 941, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(770, 30, 141, 21))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(260, 30, 141, 21))
        self.label.setObjectName("label")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(600, 60, 141, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(430, 30, 141, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_4.setGeometry(QtCore.QRect(770, 60, 141, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(600, 30, 141, 21))
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(430, 60, 141, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(260, 60, 141, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(60, 130, 161, 41))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(60, 220, 161, 41))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(60, 310, 161, 41))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(60, 370, 851, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(60, 190, 851, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(60, 280, 851, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(60, 100, 851, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(223, 30, 20, 441))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(400, 30, 20, 441))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(570, 30, 20, 441))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(740, 30, 20, 441))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(60, 460, 851, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(60, 400, 161, 41))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(420, 130, 151, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(590, 130, 151, 51))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(590, 220, 151, 51))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(760, 310, 151, 51))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_5.setGeometry(QtCore.QRect(760, 220, 151, 51))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_6.setGeometry(QtCore.QRect(760, 130, 151, 51))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_11 = QtWidgets.QFrame(self.tab_2)
        self.line_11.setGeometry(QtCore.QRect(730, 30, 20, 351))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(590, 30, 141, 21))
        self.label_9.setObjectName("label_9")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_5.setGeometry(QtCore.QRect(760, 60, 141, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setGeometry(QtCore.QRect(560, 30, 20, 351))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.tab_2)
        self.line_13.setGeometry(QtCore.QRect(220, 100, 681, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.tab_2)
        self.line_14.setGeometry(QtCore.QRect(220, 370, 681, 20))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_9.setGeometry(QtCore.QRect(580, 130, 151, 51))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.line_15 = QtWidgets.QFrame(self.tab_2)
        self.line_15.setGeometry(QtCore.QRect(220, 190, 681, 20))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_10.setGeometry(QtCore.QRect(750, 130, 151, 51))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.line_17 = QtWidgets.QFrame(self.tab_2)
        self.line_17.setGeometry(QtCore.QRect(220, 280, 681, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_6.setGeometry(QtCore.QRect(590, 60, 141, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(230, 310, 161, 41))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(230, 220, 161, 41))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(760, 30, 141, 21))
        self.label_14.setObjectName("label_14")
        self.line_18 = QtWidgets.QFrame(self.tab_2)
        self.line_18.setGeometry(QtCore.QRect(390, 30, 20, 351))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setGeometry(QtCore.QRect(420, 60, 141, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(420, 30, 141, 21))
        self.label_15.setObjectName("label_15")
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_12.setGeometry(QtCore.QRect(750, 220, 151, 51))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(230, 130, 161, 41))
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(410, 70, 141, 21))
        self.label_17.setObjectName("label_17")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(580, 70, 141, 21))
        self.label_10.setObjectName("label_10")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(230, 130, 161, 41))
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(230, 220, 161, 41))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.comboBox_13 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_13.setGeometry(QtCore.QRect(750, 220, 151, 51))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.line_16 = QtWidgets.QFrame(self.tab_3)
        self.line_16.setGeometry(QtCore.QRect(220, 370, 681, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_11.setGeometry(QtCore.QRect(750, 130, 151, 51))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_14 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_14.setGeometry(QtCore.QRect(580, 130, 151, 51))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(750, 70, 141, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(230, 310, 161, 41))
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.line_19 = QtWidgets.QFrame(self.tab_3)
        self.line_19.setGeometry(QtCore.QRect(390, 30, 20, 351))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.tab_3)
        self.line_20.setGeometry(QtCore.QRect(220, 280, 681, 20))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.tab_3)
        self.line_21.setGeometry(QtCore.QRect(220, 100, 681, 20))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.tab_3)
        self.line_22.setGeometry(QtCore.QRect(220, 190, 681, 20))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.tab_3)
        self.line_23.setGeometry(QtCore.QRect(560, 30, 20, 351))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.tab_3)
        self.line_24.setGeometry(QtCore.QRect(730, 30, 20, 351))
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(410, 70, 141, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(580, 70, 141, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(230, 130, 161, 41))
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(230, 220, 161, 41))
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.comboBox_15 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_15.setGeometry(QtCore.QRect(750, 220, 151, 51))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.line_25 = QtWidgets.QFrame(self.tab_4)
        self.line_25.setGeometry(QtCore.QRect(220, 370, 681, 20))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.comboBox_16 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_16.setGeometry(QtCore.QRect(750, 130, 151, 51))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_17 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_17.setGeometry(QtCore.QRect(580, 130, 151, 51))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(750, 70, 141, 21))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(230, 310, 161, 41))
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.line_26 = QtWidgets.QFrame(self.tab_4)
        self.line_26.setGeometry(QtCore.QRect(390, 30, 20, 351))
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.tab_4)
        self.line_27.setGeometry(QtCore.QRect(220, 280, 681, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.tab_4)
        self.line_28.setGeometry(QtCore.QRect(220, 100, 681, 20))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.tab_4)
        self.line_29.setGeometry(QtCore.QRect(220, 190, 681, 20))
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(self.tab_4)
        self.line_30.setGeometry(QtCore.QRect(560, 30, 20, 351))
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(self.tab_4)
        self.line_31.setGeometry(QtCore.QRect(730, 30, 20, 351))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(410, 70, 141, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(580, 70, 141, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(230, 130, 161, 41))
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(230, 220, 161, 41))
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.comboBox_18 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_18.setGeometry(QtCore.QRect(750, 220, 151, 51))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.line_32 = QtWidgets.QFrame(self.tab_5)
        self.line_32.setGeometry(QtCore.QRect(220, 370, 681, 20))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.comboBox_19 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_19.setGeometry(QtCore.QRect(750, 130, 151, 51))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_20 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_20.setGeometry(QtCore.QRect(580, 130, 151, 51))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(750, 70, 141, 21))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(230, 310, 161, 41))
        self.label_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.line_33 = QtWidgets.QFrame(self.tab_5)
        self.line_33.setGeometry(QtCore.QRect(390, 30, 20, 351))
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.line_34 = QtWidgets.QFrame(self.tab_5)
        self.line_34.setGeometry(QtCore.QRect(220, 280, 681, 20))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.line_35 = QtWidgets.QFrame(self.tab_5)
        self.line_35.setGeometry(QtCore.QRect(220, 100, 681, 20))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.line_36 = QtWidgets.QFrame(self.tab_5)
        self.line_36.setGeometry(QtCore.QRect(220, 190, 681, 20))
        self.line_36.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.line_37 = QtWidgets.QFrame(self.tab_5)
        self.line_37.setGeometry(QtCore.QRect(560, 30, 20, 351))
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(self.tab_5)
        self.line_38.setGeometry(QtCore.QRect(730, 30, 20, 351))
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(340, 510, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Критерий 4:"))
        self.label.setText(_translate("Dialog", "Критерий 1:"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Критерий 2:"))
        self.textEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Критерий 3:"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Критерий 1"))
        self.label_6.setText(_translate("Dialog", "Критерий 2"))
        self.label_7.setText(_translate("Dialog", "Критерий 3"))
        self.label_8.setText(_translate("Dialog", "Критерий 4"))
        self.comboBox.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_3.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_4.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_4.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_4.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_5.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_5.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_5.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_6.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_6.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_6.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Критерии"))
        self.label_9.setText(_translate("Dialog", "Объект 2:"))
        self.textEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.comboBox_9.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_9.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_9.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_9.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_9.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_9.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_9.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_9.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_9.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_10.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_10.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_10.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_10.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_10.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_10.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_10.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_10.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_10.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.textEdit_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "Объект 3"))
        self.label_12.setText(_translate("Dialog", "Объект 2"))
        self.label_14.setText(_translate("Dialog", "Объект 3:"))
        self.textEdit_7.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "Объект 1:"))
        self.comboBox_12.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_12.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_12.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_12.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_12.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_12.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_12.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_12.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_12.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.label_16.setText(_translate("Dialog", "Объект 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Первый"))
        self.label_17.setText(_translate("Dialog", "Объект 1:"))
        self.label_10.setText(_translate("Dialog", "Объект 2:"))
        self.label_18.setText(_translate("Dialog", "Объект 1"))
        self.label_13.setText(_translate("Dialog", "Объект 2"))
        self.comboBox_13.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_13.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_13.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_13.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_13.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_13.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_13.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_13.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_13.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_11.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_11.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_11.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_11.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_11.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_11.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_11.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_11.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_11.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_14.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_14.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_14.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_14.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_14.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_14.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_14.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_14.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_14.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.label_19.setText(_translate("Dialog", "Объект 3:"))
        self.label_20.setText(_translate("Dialog", "Объект 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Второй"))
        self.label_21.setText(_translate("Dialog", "Объект 1:"))
        self.label_22.setText(_translate("Dialog", "Объект 2:"))
        self.label_23.setText(_translate("Dialog", "Объект 1"))
        self.label_24.setText(_translate("Dialog", "Объект 2"))
        self.comboBox_15.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_15.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_15.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_15.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_15.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_15.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_15.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_15.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_15.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_16.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_16.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_16.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_16.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_16.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_16.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_16.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_16.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_16.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_17.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_17.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_17.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_17.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_17.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_17.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_17.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_17.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_17.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.label_25.setText(_translate("Dialog", "Объект 3:"))
        self.label_26.setText(_translate("Dialog", "Объект 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Третий"))
        self.label_27.setText(_translate("Dialog", "Объект 1:"))
        self.label_28.setText(_translate("Dialog", "Объект 2:"))
        self.label_29.setText(_translate("Dialog", "Объект 1"))
        self.label_30.setText(_translate("Dialog", "Объект 2"))
        self.comboBox_18.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_18.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_18.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_18.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_18.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_18.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_18.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_18.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_18.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_19.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_19.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_19.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_19.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_19.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_19.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_19.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_19.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_19.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.comboBox_20.setItemText(0, _translate("Dialog", "одинаково"))
        self.comboBox_20.setItemText(1, _translate("Dialog", "немного лучше"))
        self.comboBox_20.setItemText(2, _translate("Dialog", "лучше"))
        self.comboBox_20.setItemText(3, _translate("Dialog", "значительно лучше"))
        self.comboBox_20.setItemText(4, _translate("Dialog", "принципиально лучше"))
        self.comboBox_20.setItemText(5, _translate("Dialog", "немного хуже"))
        self.comboBox_20.setItemText(6, _translate("Dialog", "хуже"))
        self.comboBox_20.setItemText(7, _translate("Dialog", "значительно хуже"))
        self.comboBox_20.setItemText(8, _translate("Dialog", "принципиально хуже"))
        self.label_31.setText(_translate("Dialog", "Объект 3:"))
        self.label_32.setText(_translate("Dialog", "Объект 3"))
        self.pushButton.setText(_translate("Dialog", "Решить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Четвёртый"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
